// Product
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

// Cart
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const INCREASE_COUNT_SUCCESS = 'INCREASE_COUNT_SUCCESS';
export const DECREASE_COUNT_SUCCESS = 'DECREASE_COUNT_SUCCESS';
export const CHANGE_COUNT_SUCCESS = 'CHANGE_COUNT_SUCCESS';
